#!/usr/bin/env python3
"""
N1 host smoke -- local TLS Gemini test server.

Speaks just enough Gemini over TLS for the gmclassicnet_smoke client: read a
`gemini://host/path<CRLF>` URL line, answer `20 text/gemini<CRLF><body>`, then
close. Verified against a throwaway CA generated by scripts/test-classicnet-n1.sh
(the server cert's CN/SAN must match the hostname the client connects with).

Usage:
  gemini_tls_server.py <cert.pem> <key.pem> <port>
"""
import socket
import ssl
import sys


def main():
    cert, key, port = sys.argv[1], sys.argv[2], int(sys.argv[3])

    ctx = ssl.SSLContext(ssl.PROTOCOL_TLS_SERVER)
    ctx.minimum_version = ssl.TLSVersion.TLSv1_2
    ctx.maximum_version = ssl.TLSVersion.TLSv1_2
    ctx.load_cert_chain(certfile=cert, keyfile=key)

    body = "Hello from the N1 ClassicNet host smoke!\r\nThis is a Gemini body.\r\n"
    resp = ("20 text/gemini\r\n" + body).encode("ascii")

    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as srv:
        srv.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
        srv.bind(("127.0.0.1", port))
        srv.listen(8)
        sys.stdout.write("ready\n")
        sys.stdout.flush()
        while True:
            conn, _ = srv.accept()
            with conn:
                try:
                    with ctx.wrap_socket(conn, server_side=True) as tls:
                        tls.settimeout(10)
                        req = bytearray()
                        while b"\r\n" not in req:
                            chunk = tls.recv(4096)
                            if not chunk:
                                break
                            req += chunk
                        tls.sendall(resp)
                except ssl.SSLError:
                    pass
                except ConnectionError:
                    pass


if __name__ == "__main__":
    main()
